DATA:
    ROOT: '/mnt/sdb/data/jingyinuo/animal_kingdom/video'
    TRAIN_FILE: '/mnt/sdb/data/jingyinuo/animal_kingdom/train_animal.txt' #00
    VAL_FILE: '/mnt/sdb/data/jingyinuo/animal_kingdom/test_animal.txt'
    DATASET: animal kingdom
    NUM_FRAMES: 8
    NUM_CLASSES: 140
    LABEL_LIST: '/mnt/sdb/data/jingyinuo/animal_kingdom/label.csv'
    MULTI_CLASSES: True
    NUM_ANIMAL_CLASSES: 958
    ANIMAL_LABEL_LIST: '/mnt/sdb/data/jingyinuo/animal_kingdom/animal_label.csv'
MODEL:
    ARCH: ViT-B/16
TRAIN:
    BATCH_SIZE: 16 # 16
    ACCUMULATION_STEPS: 4
    EPOCHS: 30